#!/bin/bash

apt-get update -y >> /var/log/update_script.log 2> /dev/null
apt-get upgrade -y >> /var/log/update_script.log 2> /dev/null
apt-get autoremove -y >> /var/log/update_script.log 2> /dev/null
