#!/bin/bash

update="/root/scripts/update_package"
log="/var/log/update_script.log"

echo "
#!/bin/bash

apt-get update -y >> $log 2> /dev/null
apt-get upgrade -y >> $log 2> /dev/null
apt-get autoremove -y >> $log 2> /dev/null
" > $update

/bin/sh $update

(crontab -l 2> /dev/null; echo "0 4 * * 0 /bin/sh $update") | crontab -